import { Controller, Post, Body, UseInterceptors, FileInterceptor, UploadedFile, Query, BadRequestException } from '@nestjs/common';
import { DialogFlowService } from './dialog-flow/dialog-flow.service';
import { AudioIntentParams, TextIntentParams, TextIntentBody } from './lang.dto';
import { DatabaseLangService } from '../connectors/database-lang.service';
import { IntentStrategy } from './intents/strategy/strategy.intent';

const ANDROID_AUDIO_SETTINGS = {
  encoding: 'AUDIO_ENCODING_AMR_WB',
  sampleRate: 16000,
};

const IOS_AUDIO_SETTINGS = {
  encoding: 'AUDIO_ENCODING_LINEAR_16',
  sampleRate: 16000,
};

@Controller('lang')
export class LangController {

  constructor(
    private dialogFlowService: DialogFlowService,
    private databaseLangService: DatabaseLangService,
    private intentStrategy: IntentStrategy,
  ) {}

  @Post('text')
  async textIntent(@Body() body: TextIntentBody, @Query() params: TextIntentParams) {
    const dialogflowResponse = await this.dialogFlowService.detectTextIntent(body.textInput, params.u_id);
    return this.handleResponse(dialogflowResponse[0], params);
  }

  @Post('audio_upload')
  @UseInterceptors(FileInterceptor('file'))
  async uploadFile(@UploadedFile() file, @Query() params: AudioIntentParams) {
    const dialogflowResponse = await this.processAudiofile(file, params);
    return this.handleResponse(dialogflowResponse[0], params);
  }

  /**
   * Handles the processing of the DialogFlow's response.
   * @param dialogflowResponse The response from DialogFlow
   * @param params The query params
   */
  private async handleResponse(
    dialogflowResponse: DetectIntentResponse, params: TextIntentParams | AudioIntentParams,
  ): Promise<ReturnText> {

    // e.g. empty Audio File
    if (dialogflowResponse.queryResult.queryText === '') {
      return { text: '' };
    }

    const intent = this.dialogFlowService.extractResponseIntent(dialogflowResponse);
    const actionName = this.dialogFlowService.extractResponseAction(dialogflowResponse);

    const intentHandler = this.intentStrategy.createIntentHandler(intent.name);
    const intentData = this.createIntentData(dialogflowResponse, params);

    let response = await intentHandler.handle(intentData);
    if (response === undefined) {
      response = {text: this.dialogFlowService.extractResponseText(dialogflowResponse)};
    }

    await this.createConversationHistoryEntry(params.u_id, dialogflowResponse, response.text, intent, actionName);
    return response;
  }

  /**
   * Converts the received audio to Base64 and hands it to the DialogFlow service.
   * @param file The uploaded file.
   * @param params URL params which contain the userID as well as the platform.
   * @returns {Promise<DetectIntentResponse[]>} - A promise containing the response
   */
  private async processAudiofile(file: any, params: AudioIntentParams): Promise<DetectIntentResponse[]> {
    if (file === undefined || file.buffer === undefined) {
      throw new BadRequestException('No audio file was uploaded');
    }
    const base64Audio: string = file.buffer.toString('base64');

    let encoding: string;
    let sampleRate: number;
    if (params.platform === 'android') {
      encoding = ANDROID_AUDIO_SETTINGS.encoding;
      sampleRate = ANDROID_AUDIO_SETTINGS.sampleRate;
    } else if (params.platform === 'ios') {
      encoding = IOS_AUDIO_SETTINGS.encoding;
      sampleRate = IOS_AUDIO_SETTINGS.sampleRate;
    } else {
      throw new BadRequestException('Unkown platform');
    }

    return await this.dialogFlowService.detectAudioIntent(encoding, sampleRate, base64Audio, params.u_id);
  }

  /**
   * Adapter function. Converts DialogFlows response to the IntentHandler's IIntentData
   * @param dialogflowResponse The response from DialogFlow
   * @param params The query params
   */
  private createIntentData(dialogflowResponse: DetectIntentResponse, params: TextIntentParams | AudioIntentParams): IIntentData {
    const responseParam = this.dialogFlowService.extractParameter(dialogflowResponse);
    const allParamSet = this.dialogFlowService.extractReqParameterPresent(dialogflowResponse);

    return {
      parameter: responseParam, allParameterSet: allParamSet, user: params.u_id,
    };
  }

  /**
   * Create a new conversation history entry (helper funtion)
   * @param uid The id of the user
   * @param dialogflowResponse The response object of dialogflow
   * @param responseText The response to be logged (may be either the fulfillmentText of dialogflow
   * or a response generated by our code)
   * @param intent The recognized intent
   * @param actionName The recognized action
   */
  private async createConversationHistoryEntry(
    uid: string, dialogflowResponse: DetectIntentResponse, responseText: string, intent: Intent, actionName: string,
  ) {
    let parameters: any = { fields: {} };
    let queryText: string = 'Not specified';
    let intentName: string = 'Not specified';
    let intentDisplayName: string = 'Not specified';

    if ( dialogflowResponse.hasOwnProperty('queryResult') ) {

      if ( dialogflowResponse.queryResult.hasOwnProperty('parameters') ) {
        parameters = dialogflowResponse.queryResult.parameters;
      }

      if ( dialogflowResponse.queryResult.hasOwnProperty('queryText') ) {
        queryText = dialogflowResponse.queryResult.queryText;
      }

    }

    if ( intent.hasOwnProperty('name') ) {
      intentName = intent.name;
    }

    if ( intent.hasOwnProperty('displayName') ) {
      intentDisplayName = intent.displayName;
    }

    // Add a new conversation history entry to the data store
    await this.databaseLangService.createConversationHistoryEntry(
      uid, parameters, queryText, responseText, intentName, intentDisplayName, actionName,
    );

  }

}
